### ISSUE TITLE
Paid support/Product support page

### ISSUE THREAD

**Issue by highacid** [michael-cannon/custom-bulkquick-edit#70]
Hello,

I have purchased this product long ago from your first site, then you migrated to a new one, and now I cannot find a source to download updates for the plugin, any idea? Is this Github maintained, where is the paid product now...

**Comment by subharanjanm** [comment]
Hi @highacid ,

I am sorry about the trouble.

Please visit https://store.axelerant.com/profile/#Download_History to login and then click on "View Details and Downloads" for downloading your purchases again.

If you purchased using a guest account, then you'll need to convert to a real account via https://store.axelerant.com/convert-guest-account-to-real/ for download access.

If you need any help, please create a ticket in https://nodedesk.zendesk.com and I'd be happy to assist.

Thanks,
Subh
